name: yefa
description: "Yefa daily motivation task app"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

    # State Management & Architecture
  stacked: ^3.4.2
  stacked_services: ^1.2.0
  get_it: ^7.6.4

   # Navigation
  go_router: ^12.1.3

    # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

    # Network
  dio: ^5.3.2
  connectivity_plus: ^5.0.2

    # UI
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

    # Utils
  logger: ^2.0.2+1
  equatable: ^2.0.5
 
  cupertino_icons: ^1.0.8

dev_dependencies:
  audioplayers: ^5.2.1
  flutter_test:
    sdk: flutter

  # Code Generation
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
 
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true

 
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/


 

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
 
