server:
  name: "yefe"
  host: "localhost"
  port: 8080
  secret: ${JWT_SECRET}
  invite_url: ${INVITE_URL}
  environment: ${ENV}
  allowed_hosts: ${ALLOWED_HOSTS}
  super_admin_email: ${SUPER_ADMIN_EMAIL}
  super_admin_password: ${SUPER_ADMIN_PASSWORD}

persistence:
  postgres:
    host: ${DB_HOST}
    port: ${DB_PORT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    username: ${REDIS_USER}
    password: ${REDIS_PASSWORD}

email_config:
  from_email: ${FROM_EMAIL}
  from_name: ${FROM_NAME}
  use_tls: false
  worker_count: 2 
  queue_size: 100 
  retry_attempts: 2 
  retry_delay: 10s 
  use_smtp: ${USE_SMTP}
  smtp_email_config:
      smtp_server: ${SMTP_SERVER}
      smtp_host: ${SMTP_HOST}
      smtp_port: ${SMTP_PORT}
      smtp_username: ${SMTP_USERNAME}
      smtp_password: ${SMTP_PASSWORD}
  resend_email_config:
    resend_api_key: ${RESEND_API_KEY}

payment_config:
  stripe_secret_key: ${STRIPE_SECRET_KEY}
  pro_plan_price: 5
  paystack_private_key: ${PAYSTACK_API_KEY}
  store_paystack_webhookURL: ${PAYSTACK_WEBHOOK_URL}

firebase_config:
  type: ${FIREBASE_TYPE}
  project_id: ${FIREBASE_PROJECT_ID}
  private_key_id: ${FIREBASE_PRIVATE_KEY_ID}
  private_key: ${FIREBASE_PRIVATE_KEY}
  client_email: ${FIREBASE_CLIENT_EMAIL}
  client_id: ${FIREBASE_CLIENT_ID}
  auth_uri: ${FIREBASE_AUTH_URI}
  token_uri: ${FIREBASE_TOKEN_URI}
  auth_provider_x509_cert_url: ${FIREBASE_AUTH_PROVIDER_X509_CERT_URL}
  client_x509_cert_url: ${FIREBASE_CLIENT_X509_CERT_URL}
  universe_domain: ${FIREBASE_UNIVERSE_DOMAIN} 
