server:
  name: "yefe"
  host: "localhost"
  port: 8080
  secret: ${JWT_SECRET}

persistence:
  postgres:
    host: ${DB_HOST} 
    port: ${DB_PORT}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD} 
    database: ${DB_NAME} 
  redis:
    host: ${REDIS_HOST} 
    port: ${REDIS_PORT}
